# Generated by Django 2.0.2 on 2018-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('usedName', models.CharField(default='', max_length=255, verbose_name='曾用名')),
            ],
        ),
    ]
