# Generated by Django 2.0.2 on 2018-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcode',
            name='isdelisted',
            field=models.SmallIntegerField(default=0, verbose_name='是否退市'),
        ),
        migrations.AddField(
            model_name='stockcode',
            name='isindex',
            field=models.SmallIntegerField(default=0, verbose_name='是否指数'),
        ),
        migrations.AddField(
            model_name='stockcode',
            name='market',
            field=models.IntegerField(choices=[(0, '深市'), (1, '沪市')], default=0, verbose_name='市场'),
        ),
    ]
