# Generated by Django 2.0.2 on 2018-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangges', '0002_auto_20180406_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='isindex',
            field=models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=0, verbose_name='是否指数'),
        ),
    ]
