# Generated by Django 2.0.2 on 2018-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangges', '0003_auto_20180406_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='isdelisted',
            field=models.SmallIntegerField(choices=[(False, '否'), (True, '是')], default=0, verbose_name='是否退市'),
        ),
    ]
